### ISSUE TITLE
Rename repo?

### ISSUE THREAD

**Issue by alexsoble** [invinst/chicago-police-data#15]
The repo name is `shootings-data`, but it contains more than shootings data. Shall we rename? Great suggestion from @shua123.

**Comment by DGalt** [comment]
This goes to a question I posed last night - are we focusing on shootings (and tasings), or looking at all instances of violent interactions between police / citizens. shootings-append.csv, for example, contains a subset of the April dataset that corresponds to only shootings and tasings (i.e. the CATEGORY_CODE - either initial or current - for the incidence begins with 18, 20, or S)

**Comment by rajivsinclair** [comment]
Valid points. I think [@ChaclynHunt](https://twitter.com/chaclynhunt/) is the best judge for this.

**Comment by jayqi** [comment]
Reviving this old issue since it's important and never got addressed. I propose something like

* "Chicago Police Misconduct Data" <-> chi-police-data

**Comment by alexsoble** [comment]
@jayqi Yes I think that's a wonderful suggestion. I think the idea of one repo with all the flat files of the police data (i.e. "one repo to rule them all") is a gorgeous long-term vision and chi-police-data captures that well.

**Comment by jayqi** [comment]
Something that came to mind for the expanded title is that we might want something more neutral. While we do have a set of definitely misconduct data (the complaints from CPDB), the incidents in the use-of-force datasets from the FOIAs are not necessarily all cases of misconduct. Something like

* Chicago Police Incidents Data

or 

* Chicago Police Incidents and Complaints Data

would be a more objective label. 

Obviously, misconduct is what we're interested in, and that could be something that is discussed in the README and wiki, but a blanket judgment might not be appropriate for the title.

**Comment by jayqi** [comment]
After discussion at ChiHackNight on July 19, we renamed the repo name to `chicago-police-data`. 

Right now the working prose title (i.e. what goes at the top of the README) is "Chicago Police Incidents Data". Going to keep this thread open for a few days in case anyone wants to discuss changing that still.

**Comment by DGalt** [comment]
I'd argue that `chicago-police-data` is a bit vague / broad. I think `cpd-incidents-data` or `cpd-accountability-data` is a bit more descriptive. Unless the goal is to bring in data sets that are generally about cpd, and not specifically about use-of-force events / complaints

**Comment by jayqi** [comment]
This was something that was brought up and discussed. One point is that we don't want the shorthand repo name to be too long, and the other is that we do actually have other datasets like list of CPD employees. 

I don't like `cpd` as much as `chicago-police` because it's a lot easier for people to look at the latter at a glance and know what it's about.
