### ISSUE TITLE
Double-check data in /Clean/May2016 folder

### ISSUE THREAD

**Issue by yahwes** [invinst/chicago-police-data#19]
Data was created in pull request #17

**Comment by alexsoble** [comment]
@rajivsinclair and @ithinkidunno – do you have your own attempts at merged / clean data that we can check against @yahwes's?

**Comment by DGalt** [comment]
(posted in slack, but figure it should go here too)
So I started looking at this as well - @yahwes did you do when there was no obvious match. E.g. when there is a nan in the the Complaint_Number column, or if there is a Complaint_Number in one of the sheets in the pair but not other (e.g. 2012 Parties has the complaint number 10521242, but this does not exist in the 2012 Incid sheet)

**Comment by alexsoble** [comment]
@dgalt yeah I think doing as much of the work as possible in public is
👍🏽👍🏽👍🏽

**Comment by yahwes** [comment]
_(posted in slack, but figure it should go here too)_
The 2012 CRID 1052142 is the only one that was in "parties" but not in "incid". In that case, the values I pulled in for the 13 columns in "incid" only (Beat:Incident_Time_End, CLOSEDATIPRA_DATETIME, Report_Status:Penalty_Status), are left blank.

**Comment by DGalt** [comment]
Going through @yahwes's process I get the same thing

**Comment by alexsoble** [comment]
👍🏽👍🏽

Anything else we should document here?

@yahwes what is a .feather file?

**Comment by yahwes** [comment]
It's the new Python/R dataframe format.

**Comment by alexsoble** [comment]
Gotcha, thanks! @yahwes
