### ISSUE TITLE
What does "inmate" mean?

### ISSUE THREAD

**Issue by akashpi** [invinst/chicago-police-data#42]

**Comment by banoonoo2** [comment]
Which file are you looking at? In the clean May data, "inmate" is used in the "Invovled_Party_Type" field to indicate a PO directly involved in a firearms discharge (i.e., a PO who shot someone or was present when someone was shot). For example, Jason Van Dyke is listed as "inmate" on CRID 1072125 (Laquan McDonald).

**Comment by evanwsun** [comment]
What's the difference between inmate and witness when there's more than one inmate, but police officers are listed as both inmates and witnesses?

**Comment by banoonoo2** [comment]
Just realized I didn't reply yet! Generally speaking, the "inmate" POs allegedly did something wrong, while the "witness" POs just saw what happened, either as it happened or the aftermath. For example:

1079080 PO who fired gun and his partner are "inmates." Other POs who arrived on the scene and arrested a second, on-DoA person are "witnesses."

1079661 2 POs who fired guns are "inmates." Of 2 POs on scene who didn't shoot, 1 is an "inmate" and 1 is a "witness." Not sure why.

1073787 2 POs who fired guns are "inmates." 3rd PO who was with them but didn't shoot plus 2 more POs who didn't shoot are "witnesses."
