### ISSUE TITLE
Basic projects/work that newcomers can tackle?

### ISSUE THREAD

**Issue by evanwsun** [invinst/chicago-police-data#43]
Today we had a lot of new people come in, and while I was able to get them somewhat up to date on all of the data, I wasn't sure what work they should tackle next. What are some basic projects that these people could work on to get a feel for the data as well as contribute?

**Comment by jayqi** [comment]
I think the two main categories of things to do are:

* Contribute to repo reorganization project. I'm trying to open up tickets for these tasks to make sure that this is all clear. Includes:
    * Reorganizing the files
    * Writing up documentation
    * Writing up the newcomer guide

* Work on independent projects. 
    * Any of the yellow "independent project" tags are questions about the data that have been posed at various points. Most of them probably never got finished.
    * Start up a new independent project! If there's any interesting ideas for analysis to do, one can always go for it. Open up a ticket so other people know what you're working on, specify if you want help or not, and someone with admin privileges can mark it with an independent project tag.
