### ISSUE TITLE
Decimal ages in June data

### ISSUE THREAD

**Issue by evanwsun** [invinst/chicago-police-data#47]
@DGalt How were the decimal ages determined? Was it taking into account month and day as well as year?

**Comment by DGalt** [comment]
So, this is something odd. If you look at the raw excel files, there are no decimals. But if you look at the actual fields (open the file in excel, click on a cell, and look at the value in the entry box) there is a decimal value. E.g. the female victim for CRID 1039179 has what looks like an age of 26 if you just look at the file, but the cell has an actual value of 25.832877 - which is what is in the data files I've provided. 

How CPD calculated those ages I do not know. My guess is what you suggested, but I don't know. We can just round them to integers if we want.
