### ISSUE TITLE
Missing FOIA documents

### ISSUE THREAD

**Issue by jayqi** [invinst/chicago-police-data#56]
What we're missing:
- `shootings-ipra-may2016` - FOIA request and/or response
- `complaints-ipra-apr2016` - FOIA request (we have responses but they don't quote the requests in detail)
- `cpdb_complaints-cpd` - FOIA requests and/or responses for `august 2015`, `march 2015`, and `september 2015`

**Comment by chaclyn** [comment]
- shootings-cpd-february2016
request: https://www.documentcloud.org/documents/2995716-FOIAU-FileCPD.html
response: (will collect from Jamie Kalven, who is the filer & receiver on the request.)

- shootings-ipra-may2016
request: https://www.documentcloud.org/documents/2995650-FOIAU-FileIRPA04072016.html 
response: https://www.documentcloud.org/documents/2995713-IPRA-U-Files-Response-Letter.html
(includes three separate letters - an extension, an update, and a final)

- complaints-ipra-apr2016
request: https://www.documentcloud.org/documents/2995647-DataUpdateIPRA04072016.html 
response: https://www.documentcloud.org/documents/2995715-IPRA-misconduct-april-response-letter.html

- cpdb_complaints-cpd march2015
request: https://www.documentcloud.org/documents/2995647-DataUpdateIPRA04072016.html (this is an identical request, just updated with a date to send to IPRA later)
response: (will collect from Jamie Kalven, who is the filer & receiver on the request.)

- category codes
request: https://www.documentcloud.org/documents/2995653-FOIACategoryCodes-2.html
response IPRA: https://www.documentcloud.org/documents/2642470-311-Response.html 
response CPD: https://www.documentcloud.org/documents/2642471-Scan-001.html 

- TRR data request, no answer / no data set
request: https://www.documentcloud.org/documents/2995649-TRRFOIA.html

- assignment data + officer demographics
request: fully contained in the response, written in the body of an e-mail
response: https://www.documentcloud.org/documents/2995717-Kalven-16-1105-Responsive-Letter.html 

that's most of what i could find for now! will update here at some point.

**Comment by jayqi** [comment]
Questions:

* `shootings-cpd-feb2016`
    * You provided a request letter 10/30/2015. We already had a final response letter dated 1/29/2016. However, the contents of that letter reference a 11/17/2015 response letter from CPD to Jamie Kalven, and then a new request letter with narrowed constraints from Jamie Kalven to CPD of unknown date but labeled "FOIA FILE NO. 15-7058". Can we get those two missing letters?
* `shootings-ipra-may2016`
    * Reading into the three letters you've combined as the responses, it seems like there might be a data file that is missing from our repo. The second response letter ("update", 4/21/2016) says it accompanies a spreadsheet. The third response letter ("final", 5/20/2016) says that in addition to the one previous spreadsheet, it is accompanying 14 additional spreadsheets. Right now the Excel file we have in the repo has 14 worksheets (the fifteenth Sheet3 is blank), so I presume that file is what the third letter is talking about. What about the single spreadsheet that the second letter talks about? 
* `complaints-ipra-apr2016` - the repo originally had two response letters. One is the same as the one you've linked to, and the other is actually the second response letter from the shootings-ipra-may2016 set above. Is it a mistake that this shootings response letter is in the April complaints folder? The response letter says there are five spreadsheets, but the folder has two extra ones: `IPRA Investigators' Info.xls` and `Shootings Victim Data.xls`. Is the victim spreadsheet the missing one from the May set that I asked about above? What about the investigator spreadsheet -- where did that come from?
