### ISSUE TITLE
Processing on October 2016 FOIA 

### ISSUE THREAD

**Issue by pjsier** [invinst/chicago-police-data#72]
I didn't see any details under the `complaints-cpd-2016-october`, on cleanup, but if it's still something you're looking for I've taken a stab at it here [chicago-police-data-cleanup](https://github.com/pjsier/chicago-police-data-cleanup). The overall totals I'm getting roughly match up with the [Tribune's counts](http://www.chicagotribune.com/news/watchdog/ct-chicago-police-complaints-met-20161013-story.html), but I'm not sure if there are any details in particular I'm overlooking.

**Comment by rajivsinclair** [comment]
thanks! @pjsier 
the last time we cleaned up a similarly structured dataset (cpd-complaints-june-2016) we used this method: https://gist.github.com/DGalt/6b419549086d3aadff8b7cc072fc60b3
